### ISSUE TITLE
[Feature Request] Documentation

### ISSUE THREAD

**Issue by alexamacbett** [anvil-vtt/FateX#106]
**Is your feature request related to a problem? Please describe.**
The only available documentation is FateX's readme, which makes oblique references to the system's selling points and unique features but makes no attempt to explain what these actually are or how they work. The user is left to try and figure out what functional features FateX even has on their own and what things like the actor template system even are.

**Describe the solution you'd like**
The system has documentation that explains in detail how to set up a world concordant with a custom Fate Core, FAE or Fate Condensed game, including how the actor template system works and how to create a preset that replaces things like the default skill list and lack of extras with your game's own. It also explains what features FateX has and why it would preferable to other Foundry Fate systems.

This documentation is linked to clearly in all places the system is vended.

**Comment by PatrickBauer** [comment]
Thanks for your suggestion. To be honest, its a lot of work to write documentation and even more work to keep it updated and consistent. If you'd write this documentation and provide me with it, I'd be happy to incorporate it into the system.

**Comment by alexamacbett** [comment]
That is understandable, however even if I were willing to do this and had the time, I was unable to make head nor tail of FateX or even identify any actual features it had without existing documentation and switched to using Fate Core Official personally, so I wouldn't be able to write anything productive.
