### ISSUE TITLE
[Object: Promise] replaces description fields on Forge 11

### ISSUE THREAD

**Issue by IcedQuinn** [anvil-vtt/FateX#112]
- Create a new character sheet
- Add a stunt or an extra
- Observe that the description is listed as `[Object: Promise]`
- Assign a description to the stunt or extra
- Observe the description does not save
- Observe that when re-opening the editor the content has returned to `[Object: Promise]`

This does not happen to every text field. Names of stunts, extras, and so on, continue to work absolutely fine.

**Comment by PatrickBauer** [comment]
Thank you for this bug report. Right now, FateX is not yet supported on Foundry v11 yet. An update is on the way though! :)

**Comment by PatrickBauer** [comment]
The system is now compatible with v11 and should work again 🙂

**Comment by IcedQuinn** [comment]
> The system is now compatible with v11 and should work again 🙂

Wonderful I will try to test it some time this week.

**Comment by IcedQuinn** [comment]
Confirmed that editing the textual descriptions works. No more Object Promise :+1:
