### ISSUE TITLE
Confirm V11 Compatibility

### ISSUE THREAD

**Issue by RinVindor** [anvil-vtt/FateX#113]
Currently Foundry still states the system is last verified as working with V9, my friends have been playing fine on V10 but are hesitant to update further without it being listed as having support. Thanks for the hard work!

**Comment by PatrickBauer** [comment]
Thats interesting, the system should have been shown as compatible with v10 for a long time. 
https://foundryvtt.com/packages/fatex

But yes, its not yet compatible with v11 yet, but hopefully soon! :)

**Comment by PatrickBauer** [comment]
The system is now compatible with v11 🥳
