### ISSUE TITLE
Version 1.2.4, the Version 11 compatible 

### ISSUE THREAD

**Issue by hendelmasad** [anvil-vtt/FateX#114]
Thanks for the update of the V11 compatible version of Fate X. I did find that text carries on into the stress tracks if your make the character window smaller. See file attached.
![Screenshot (5)](https://github.com/anvil-vtt/FateX/assets/87272867/96929be4-c718-4f29-8fd6-cddf0737006f)

**Comment by PatrickBauer** [comment]
Hey @hendelmasad
Thank you for testing this new release. 

I just pushed an update which should prevent this overflowing behaviour. But this should only happen when the content width inside the stunt is bigger than the container. I'm suspecting the box with the "Mild:" content to be the culprit. It may be, that in the new version you'll se a scrollbar inside the stunts text area.

**Comment by hendelmasad** [comment]
Thank you for the speedy response and I'll have a quick look right away!

**Comment by hendelmasad** [comment]
You were quite right. A Lateral scroll bar appeared and when I deleted the Mild consequence link, it fixed it.
