### ISSUE TITLE
Skills can be rolled too easily in edit mode

### ISSUE THREAD

**Issue by DavidENishball** [anvil-vtt/FateX#14]
When editing a character sheet, such as moving around the skill list, it is too easy to click the name of the skill and cause a roll, which puts an entry into the chat log.  This can give away actors I don't want revealed to the players, and requires me to delete the unused rolls from the log.  Please either disable rolling while the sheet is in edit mode, make a smaller button for rolling, or have rolls on the character sheet obey the chat's current permission level (self roll, public roll, gm only, etc)

**Comment by PatrickBauer** [comment]
Thank you for reporting! I'll probably disable the button when the edit-mode is active.

**Comment by PatrickBauer** [comment]
@DavidENishball 
Fixed in 0.7.2 which released today. 👍
