### ISSUE TITLE
Bug: Changes to skill rank not reflected in dice rolls

### ISSUE THREAD

**Issue by doct** [anvil-vtt/FateX#22]
When a character sheet is put in edit mode, and the skill rank is changed, then the edit mode closed, on the char sheet, the skill has the new rating.
However, then clicking on the skill to roll the dice results in a dice roll taking the previous skill rank into account, but does not use the new rank.
Only after a reload of the game session, e.g. by leaving and reentering the world, or by going to the "Game Settings" -> "Module Management" dialog, not changing anything but hitting "Save Module Settings" to force a reload, are the new skill values taken into account upon rolling the dice.

Thanks for your awesome system module!

**Comment by PatrickBauer** [comment]
@doct Thank you for reporting this bug. Are you still on FoundryVTT 0.6 or have you updated to 0.7.5? 
I'll try to reproduce it tomorrow 😁 👍

**Comment by doct** [comment]
Wow, that was fast :-) 
It's on FoundryVTT 0.7.5 using FateX 0.7.7.

**Comment by PatrickBauer** [comment]
@doct I fixed the issue and released a new version. It looks like it may be a Foundry bug I had to circumvent (speaking to Atropos right now about it). 👍

**Comment by doct** [comment]
Whatever you did, you did it! Thank you! :-)
