### ISSUE TITLE
[Bug] Character sheet "Bio" text area does not scale vertically

### ISSUE THREAD

**Issue by doct** [anvil-vtt/FateX#24]
Character sheets in the tab "Bio" have a descriptive text area, which is great.
The text area does scale horizontally, when the character window is enlarged horzontally.
However, vertically, the bio area has a fixed size of 9 lines. Enlarging the char sheet window vertically does not increase the text area, which, as last editable element on the page/tab, it should.

**Comment by PatrickBauer** [comment]
@doct 
What browser are you using? I'm not able to reproduce what you're reporting, but maybe we're using different browsers / versions 😁 

![Screenshot 2020-10-27 100756](https://user-images.githubusercontent.com/1428943/97280247-4fbfb400-183c-11eb-8014-9d33c337e7e4.png)

**Comment by doct** [comment]
I'm using the best browser there is, Edge/Chromium :-) I think, I see the issue. No, not the browser :-) Same with Chrome.

The vertical adaptation happens only after hitting the save button. See this image before saving:

![image](https://user-images.githubusercontent.com/767800/97315968-8c55d480-1869-11eb-9e7d-6b5296e16e56.png)

And then this after saving and editing again:

![image](https://user-images.githubusercontent.com/767800/97316059-a394c200-1869-11eb-90eb-23d0dee6e61a.png)

So maybe the redrawing/rescaling of the text area should happen during editing instead of only after, but I guess it's just a minor issue which can be ignored. Thanks for looking into it.

Interestingly, the same issue existed in the simple worldbuilding system of FVTT a long time ago, but vanished at some point.
