### ISSUE TITLE
Ladder in italian is not working (my bad)

### ISSUE THREAD

**Issue by smoothingplane** [anvil-vtt/FateX#43]
I made a mistake in the Italian translation of Fatex:

> {
>     "FateX": "FateX",
>     "FAx": {
>         "name": "FateX",
>         "Global": {
>             "**Scala**": {
>                 "+8": "Leggendario",
>                 "+7": "Epico",
>                 "+6": "Fantastico",
>                 "+5": "Eccellente",
>                 "+4": "Ottimo",
>                 "+3": "Buono",
>                 "+2": "Discreto",
>                 "+1": "Medio",
>                 "+0": "Mediocre",
>                 "-1": "Scarso",
>                 "-2": "Pessimo",
>                 "-3": "Catastrofico",
>                 "-4": "Terribile"
>             }
>  

"Scala" should be replaced with "Ladder"

I apologize.

**Comment by PatrickBauer** [comment]
Thank you, thats not a problem. Gonna fix it later today and release a new version 😁

**Comment by PatrickBauer** [comment]
Issue is fixed, thanks for reporting :)
