### ISSUE TITLE
artwork in sheet

### ISSUE THREAD

**Issue by haukefrahmann** [anvil-vtt/FateX#52]
the image is vertically centred 
big images are becoming "head of" ... looks ... nrgl

perhaps vertical align top?

![grafik](https://user-images.githubusercontent.com/15379635/115542749-e1b2f180-a2a0-11eb-93aa-44f3b6faa71b.png)

**Comment by haukefrahmann** [comment]
something for the next version .. it's just a sooo simple on :D

**Comment by Pjb518** [comment]
@PatrickBauer Should be able to close this one now, I think 🙂
