### ISSUE TITLE
[Feature request] Drag and drop pre-written stunts from compendium to actor.

### ISSUE THREAD

**Issue by Grottmastaren** [anvil-vtt/FateX#73]
Drag and drop pre-written stunts from compendium to actor.

**Comment by PatrickBauer** [comment]
@Grottmastaren Doesn't that work already? As all stunts are items, that should already work

**Comment by Pjb518** [comment]
I am able to drag stunts onto an actor sheet it the current version of FateX (0.13.0).

One slightly awkward thing is that stunts can only be dragged into the items panel of the main Foundry interface when the sheet is in edit mode. When the sheet isn't in edit mode, all pointer events are disabled, so we can't perform the drag. None of this affects dragging *to* the sheet, however.

This is also true for skills, aspects, consequences, extras, etc.

**Comment by hendelmasad** [comment]
I have no problem getting this to work. Perhaps it's been addressed and it should be marked as closed.
