### ISSUE TITLE
Actors stored in folders and exported to compendia do not retain their folders

### ISSUE THREAD

**Issue by hendelmasad** [anvil-vtt/FateX#79]
Thanks for being so receptive for direct feed back. I noticed one other thing. When I export ACTORS to compendiums, if there is a folder it doesn't get created in the compendium and the create a character template selection window pops up. Here's a quick vid:
https://screenrec.com/share/T43HxhZQFp

**Comment by PatrickBauer** [comment]
Was fixed in release 0.14.0, thanks for reporting! 👍
