### ISSUE TITLE
Checkbox to wrap templates in template picker

### ISSUE THREAD

**Issue by PatrickBauer** [anvil-vtt/FateX#97]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by hendelmasad** [comment]
Isn't this issue solved? Not with a checkbox but as default behaviour the templates render in nice neat columns and rows now. No more sideways scrolling!

**Comment by PatrickBauer** [comment]
You're right, thats the default behaviour now :)
